title: Seth Holloway
author:
  name: Seth Holloway
    #email: sethholloway@sethholloway.com
description: >
  Seth Holloway PhD, is a technology leader who tries to improve 
  everyday. Sometimes, he succeeeds.

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,         user_url: "https://github.com/sethholloway" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=IeZbwRsAAAAJ" }
    - { platform: keybase,        user_url: "https://keybase.io/sethholloway" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/sethholloway" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/553403/smholloway" }
    - { platform: twitter,        user_url: "https://twitter.com/sethholloway" }
    - { platform: rss,            user_url: "https://sethholloway.com/feed.xml" }

show_excerpts: false # set to true to show excerpts on the homepage

permalink: :title/

# Build settings
baseurl: /
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
